backend:
  name: git-gateway
  # repo: GIANNIS-AGGELIS/site-gr
  branch: master

media_folder: "_images/uploads"
public_folder: "uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "all_collections/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:

      - label: "Reference"
        name: "ref"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Excerpt"
        name: "excerpt"
        widget: "string"
      - label: "Tags"
        name: "tags"
        widget: "string"
        required:  false
      - label: "Categories"
        name: "categories"
        widget: "string"
        required:  false
      - label: "Body"
        name: "body"
        widget: "markdown"